- project:
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
    check:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
